<a href="https://colab.research.google.com/github/anakvale/analise-udemy-courses/blob/main/Projeto_T%C3%A9cnicas_de_Programa%C3%A7%C3%A3o_I_An%C3%A1lise_de_Dados_(Ana_Kelly).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Análise de Dados - Cursos plataforma de ensino *online*

Detalhes da base de dados podem ser vistos na plataforma Kaggle pelo <a href="https://www.kaggle.com/datasets/thedevastator/udemy-courses-revenue-generation-and-course-anal">link</a>

### Perguntas a serem respondidas a partir dos dados.

1. Quantos cursos estão disponíveis na plataforma?

In [ ]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
bc = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Ada - Lets Code/Diversidade Tech/M3/Desafio/3.1-data-sheet-udemy-courses-business-courses.csv')
dc = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Ada - Lets Code/Diversidade Tech/M3/Desafio/3.1-data-sheet-udemy-courses-design-courses.csv')
mc = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Ada - Lets Code/Diversidade Tech/M3/Desafio/3.1-data-sheet-udemy-courses-music-courses.csv')
wd = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Ada - Lets Code/Diversidade Tech/M3/Desafio/3.1-data-sheet-udemy-courses-web-development.csv')

df = pd.concat([bc, dc, mc, wd])
df

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
0,49798.0,Bitcoin or How I Learned to Stop Worrying and ...,https://www.udemy.com/bitcoin-or-how-i-learned...,0.0,65576.0,936.0,24.0,All Levels,0.56,8.0,2013-04-20T02:25:22Z,Business Finance
1,48841.0,Accounting in 60 Minutes - A Brief Introduction,https://www.udemy.com/accounting-in-60-minutes...,0.0,56659.0,4397.0,16.0,Beginner Level,0.95,1.5,2013-04-07T21:39:25Z,Business Finance
2,133536.0,Stock Market Investing for Beginners,https://www.udemy.com/the-beginners-guide-to-t...,0.0,50855.0,2698.0,15.0,All Levels,0.91,1.5,2013-12-25T19:53:34Z,Business Finance
3,151668.0,Introduction to Financial Modeling,https://www.udemy.com/financial-modeling-asimp...,0.0,29167.0,1463.0,8.0,All Levels,0.18,1.5,2014-05-27T16:22:16Z,Business Finance
4,648826.0,The Complete Financial Analyst Course 2017,https://www.udemy.com/the-complete-financial-a...,195.0,24481.0,2347.0,174.0,All Levels,0.37,10.0,2016-01-21T01:38:48Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...,...
1200,1227578.0,Learning Path: The Road to Elasticsearch,https://www.udemy.com/learning-path-the-road-t...,200.0,50.0,5.0,60.0,Beginner Level,0.96,5.0,2017-05-29T17:56:24Z,Subject: Web Development
1201,1277924.0,Angular 4 Front To Back,https://www.udemy.com/angular-4-front-to-back/,40.0,44.0,0.0,68.0,All Levels,0.15,8.5,2017-07-06T15:04:55Z,Subject: Web Development
1202,1248172.0,Essentials of Spring 5.0 for Developers,https://www.udemy.com/essentials-of-spring-50-...,125.0,34.0,2.0,21.0,Beginner Level,0.46,1.5,2017-06-11T18:34:40Z,Subject: Web Development
1203,1250934.0,Display and analyze GIS data on the web with L...,https://www.udemy.com/display-and-analyze-gis-...,100.0,25.0,4.0,66.0,Beginner Level,0.67,12.5,2017-06-15T21:17:43Z,Subject: Web Development
1204,1270222.0,Learning Path: Web Applications with Spring an...,https://www.udemy.com/learning-path-web-applic...,200.0,19.0,2.0,33.0,Beginner Level,0.12,4.0,2017-06-28T21:04:21Z,Subject: Web Development

In [ ]:
df.to_csv("df-projeto.csv", index=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3681 entries, 0 to 1204
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3676 non-null   float64
 1   course_title         3676 non-null   object
 2   url                  3676 non-null   object
 3   price                3676 non-null   float64
 4   num_subscribers      3676 non-null   float64
 5   num_reviews          3676 non-null   float64
 6   num_lectures         3676 non-null   float64
 7   level                3676 non-null   object
 8   Rating               3677 non-null   float64
 9   content_duration     3676 non-null   float64
 10  published_timestamp  3676 non-null   object
 11  subject              3677 non-null   object
dtypes: float64(7), object(5)
memory usage: 373.9+ KB

In [ ]:
#cursos disponíveis na plataforma
df['course_id'].nunique()

3672

2. Quais e quantos são os cursos que abordam o assunto: JavaScript?

In [ ]:
cursos_jsc = df[df['course_title'].str.contains('JavaScript', na=False)]
len(cursos_jsc)

111

3. Qual é o preço médio (coluna *price*) dos cursos oferecidos na plataforma?

In [ ]:
preco_medio = df['price'].mean()
print(f'{preco_medio:.2f}')

66.12

4. Quais são os cinco cursos com maior número de inscritos (coluna *num_subscribers*)?

In [ ]:
cursospop = df.sort_values('num_subscribers', ascending=False).head(5)
cursospop

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
0,41295.0,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0.0,268923.0,8629.0,45.0,Beginner Level,0.82,10.5,2013-02-14T07:03:41Z,Subject: Web Development
1,59014.0,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,0.0,161029.0,279.0,27.0,Expert Level,0.69,3.5,2013-06-09T15:51:55Z,Subject: Web Development
2,625204.0,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,200.0,121584.0,27445.0,342.0,Beginner Level,0.89,43.0,2015-11-02T21:13:27Z,Subject: Web Development
3,173548.0,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,0.0,120291.0,5924.0,30.0,All Levels,0.78,3.0,2014-04-08T16:21:30Z,Subject: Web Development
4,764164.0,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,200.0,114512.0,22412.0,304.0,Beginner Level,0.55,30.5,2016-03-08T22:28:36Z,Subject: Web Development

5. Dos cinco cursos mais populares em termos de inscritos, mostre o **rate médio**, **máximo** e **mínimo** de cada um deles.

In [ ]:
meanPopRating = cursospop['Rating'].mean()
print(f'O rating médio entre os cursos mais populares é {meanPopRating:.2f}')

maxPopRating = cursospop['Rating'].max()
print(f'O rating máximo entre os cursos mais populares é {maxPopRating}')

minPopRating = cursospop['Rating'].min()
print(f'O rating mínimo entre os cursos mais populares é {minPopRating}')

O rating médio entre os cursos mais populares é 0.75
O rating máximo entre os cursos mais populares é 0.89
O rating mínimo entre os cursos mais populares é 0.55

6. Apresente os dez cursos mais visualizados na plataforma.

In [ ]:
#acredito que deveriam ter sido solicitados os cursos com mais reviews, já que não há dados sobre visualizações na base. sendo assim, utilizei a variável num_reviews.
cursosav = df.sort_values('num_reviews', ascending=False).head(10).reset_index()
cursosav

,index,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
0,2,625204.0,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,200.0,121584.0,27445.0,342.0,Beginner Level,0.89,43.0,2015-11-02T21:13:27Z,Subject: Web Development
1,4,764164.0,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,200.0,114512.0,22412.0,304.0,Beginner Level,0.55,30.5,2016-03-08T22:28:36Z,Subject: Web Development
2,9,756150.0,Angular 4 (formerly Angular 2) - The Complete ...,https://www.udemy.com/the-complete-guide-to-an...,190.0,73783.0,19649.0,329.0,Beginner Level,0.90,22.0,2016-02-11T07:29:29Z,Subject: Web Development
3,8,364426.0,JavaScript: Understanding the Weird Parts,https://www.udemy.com/understand-javascript/,175.0,79612.0,16976.0,85.0,All Levels,0.69,11.5,2015-03-12T23:19:54Z,Subject: Web Development
4,21,705264.0,Modern React with Redux,https://www.udemy.com/react-redux/,180.0,50815.0,15117.0,150.0,All Levels,0.62,26.5,2015-12-28T19:20:21Z,Subject: Web Development
5,16,289230.0,Learn and Understand AngularJS,https://www.udemy.com/learn-angularjs/,175.0,59361.0,11580.0,55.0,Beginner Level,0.87,7.0,2014-09-24T00:57:25Z,Subject: Web Development
6,17,461160.0,Learn and Understand NodeJS,https://www.udemy.com/understand-nodejs/,195.0,58208.0,11123.0,98.0,Beginner Level,0.73,13.0,2015-08-31T21:07:48Z,Subject: Web Development
7,0,41295.0,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0.0,268923.0,8629.0,45.0,Beginner Level,0.82,10.5,2013-02-14T07:03:41Z,Subject: Web Development
8,28,719002.0,Angular 2 with TypeScript for Beginners: The P...,https://www.udemy.com/angular-2-tutorial-for-b...,150.0,40070.0,8341.0,194.0,All Levels,0.74,9.5,2016-03-03T20:17:59Z,Subject: Web Development
9,1,238934.0,Pianoforall - Incredible New Way To Learn Pian...,https://www.udemy.com/pianoforall-incredible-n...,200.0,75499.0,7676.0,362.0,Beginner Level,0.96,30.0,2014-08-07T06:27:51Z,Musical Instruments

7. A partir dos dez cursos mais vistos, mostre: 1) qual tem o maior número de inscritos; 2) qual tem o maior **rate** (avaliação do curso).

In [ ]:
#curso com maior número de inscritos
cursosav.sort_values('num_subscribers', ascending=False).head(1)

,index,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
7,0,41295.0,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0.0,268923.0,8629.0,45.0,Beginner Level,0.82,10.5,2013-02-14T07:03:41Z,Subject: Web Development

In [ ]:
#curso com maior nota
cursosav.sort_values('Rating', ascending=False).head(1)

,index,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
9,1,238934.0,Pianoforall - Incredible New Way To Learn Pian...,https://www.udemy.com/pianoforall-incredible-n...,200.0,75499.0,7676.0,362.0,Beginner Level,0.96,30.0,2014-08-07T06:27:51Z,Musical Instruments

8. Dos cursos listados na base de dados, qual tem maior duração em horas?

In [ ]:
df.sort_values('content_duration', ascending=False).head(1)

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
166,978576.0,The Complete Figure Drawing Course HD,https://www.udemy.com/the-complete-figure-draw...,50.0,1323.0,136.0,225.0,Beginner Level,0.37,78.5,2016-10-11T21:40:06Z,Graphic Design

9. Dos cursos listados na base de dados, qual tem o maior número de aulas (*lectures*)?

In [ ]:
df.sort_values('num_lectures', ascending=False).head(1)

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
80,79154.0,Back to School Web Development and Programming...,https://www.udemy.com/back-to-school-web-devel...,200.0,18170.0,117.0,779.0,All Levels,0.4,44.5,2013-08-19T14:53:00Z,Subject: Web Development

10. Apresente o número (contagem) de cursos agrupados por nível (coluna *level*).

In [ ]:
df.groupby(['level']).size()

level
All Levels            1925
Beginner Level        1271
Expert Level            58
Intermediate Level     422
dtype: int64

11. Quais são os cursos mais recentes contidos na base de dados?

In [ ]:
df["published_timestamp"] = pd.to_datetime(df["published_timestamp"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3681 entries, 0 to 1204
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3676 non-null   float64
 1   course_title         3676 non-null   object
 2   url                  3676 non-null   object
 3   price                3676 non-null   float64
 4   num_subscribers      3676 non-null   float64
 5   num_reviews          3676 non-null   float64
 6   num_lectures         3676 non-null   float64
 7   level                3676 non-null   object
 8   Rating               3677 non-null   float64
 9   content_duration     3676 non-null   float64
 10  published_timestamp  3676 non-null   datetime64[ns, UTC]
 11  subject              3677 non-null   object
dtypes: datetime64[ns, UTC](1), float64(7), object(4)
memory usage: 373.9+ KB

In [ ]:
#apresentando os 5 cursos mais recentes
df.sort_values('published_timestamp', ascending=False).head(5)

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
1183,1282064.0,Cryptocurrency (BTC & ETH) Investment & Tradin...,https://www.udemy.com/cryptocurrency-btc-eth-i...,20.0,0.0,0.0,7.0,All Levels,0.95,2.500000,2017-07-06 21:46:30+00:00,Business Finance
1164,1187084.0,Forex how traders beat the markest with little...,https://www.udemy.com/forex-how-traders-beat-t...,100.0,0.0,0.0,16.0,All Levels,0.15,1.000000,2017-07-06 21:16:13+00:00,Business Finance
1027,1268616.0,Condor Broken Wing Butterfly Options Trading C...,https://www.udemy.com/condor-broken-wing-butte...,0.0,16.0,0.0,15.0,All Levels,0.20,1.500000,2017-07-06 19:47:16+00:00,Business Finance
669,1265814.0,ABRSM Grade III Piano Class - Handel Sonatina ...,https://www.udemy.com/abrsm-grade-iii-piano-cl...,20.0,0.0,0.0,5.0,Beginner Level,0.34,0.516667,2017-07-06 16:12:34+00:00,Musical Instruments
1201,1277924.0,Angular 4 Front To Back,https://www.udemy.com/angular-4-front-to-back/,40.0,44.0,0.0,68.0,All Levels,0.15,8.500000,2017-07-06 15:04:55+00:00,Subject: Web Development

12. Apresente o número (contagem) de cursos agrupados por nível (coluna *level*) e por assunto (coluna *subject*).

In [ ]:
df.groupby(['level','subject']).size()

level               subject
All Levels          Business Finance            633
                    Graphic Design              335
                    Musical Instruments         324
                    Subject: Web Development    633
Beginner Level      Business Finance            399
                    Graphic Design              184
                    Musical Instruments         266
                    Subject: Web Development    422
Expert Level        Business Finance             25
                    Graphic Design                7
                    Musical Instruments          12
                    Subject: Web Development     14
Intermediate Level  Business Finance            134
                    Graphic Design               76
                    Musical Instruments          78
                    Subject: Web Development    134
dtype: int64

13. Disponibilize suas análises em um repositório do Github e compartilhe o link abaixo.

[Repositório Github](https://github.com/anakvale/analise-udemy-courses)

14. Crie uma conta no <a href="https://www.kaggle.com/datasets/thedevastator/udemy-courses-revenue-generation-and-course-anal">Kaggle</a> e crie um Notebook com as análises feitas neste projeto. A ideia aqui, é que você comece a criar um portfólio de análise de dados na plataforma :)

[Link para o Kaggle](https://www.kaggle.com/anakellyvale/analise-udemy-courses)